# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import os
from Exemple_fork import *
from Exemple_execvp import *
from Exemple_execlp import *
from Exemple_execl import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 350)

        # Les paramettres de combobox

        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(0, 30, 161, 31))

        # font de combobox
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.comboBox.setFont(font)

        self.comboBox.setObjectName("comboBox")
        list = ["Execl","Fork","Execvp",  "Execlp" ]
        self.comboBox.addItems(list)

        # bouton
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 30, 111, 31))
        self.pushButton.setAutoRepeatDelay(300)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color : grey")

        # bouton 2
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 30, 100, 31))
        self.pushButton_2.setAutoRepeatDelay(300)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("background-color : red")

        # action du bouton1
        self.pushButton.clicked.connect(self.action_bouton)
        # action du bouton2
        self.pushButton_2.clicked.connect(self.clearText)

        # label 1
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 0, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")

        # textEdit 1
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(120, 70, 271, 111))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        self.textEdit.acceptRichText()

        # textEdit 2
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 190, 271, 40))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.acceptRichText()

        # label 2
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        #label 3
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(33, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        # valeur de Bouton
        self.pushButton.setText(_translate("Form", "Executer"))

        # valeur de Bouton
        self.pushButton_2.setText(_translate("Form", "Effacer"))


        # Valeur de label 1
        self.label.setText(_translate("Form", "Choisir un programme à exécuter"))

        # Valeur de label 2
        self.label_2.setText(_translate("Form", "Explication:"))

        # Valeur de label 3
        self.label_3.setText(_translate("Form", "Résultat:"))

    def action_bouton(self):
        if self.comboBox.currentText() == "Fork":
            explication_fork = "C'est un exemple d'une fonction qui permet de creer un " \
                               "processus fork et affiche la valeur du pid du fils," \
                               "le pid du pere du fils"
            self.textEdit.setText(explication_fork)

            self.textEdit_2.setText(Fork())

        elif self.comboBox.currentText() == "Execvp":
            explication_execvp = "C'est un exemple d'une fonction qui permet de creer un " \
                               "processus fork, ce processus fils executera la" \
                               " fonction execvp et comme argument 'xclock' "
            self.textEdit.setText(explication_execvp)
            resultat = "Affiche d'une horloge"
            self.textEdit_2.setText(resultat)
            Execvp()

        elif self.comboBox.currentText() == "Execlp":
            explication_execlp = "C'est un exemple d'une fonction qui permet de creer un " \
                               "processus fork, ce processus fils executera la" \
                               " fonction execlp et comme argument 'pwd'"
            self.textEdit.setText(explication_execlp)
            resultat = "Affiche le repertoire courant sur le terminal"
            self.textEdit_2.setText(resultat)
            Execlp()

        elif self.comboBox.currentText() == "Execl":
            explication_execlp = "C'est un exemple d'une fonction qui permet de creer un " \
                               "processus fork, ce processus fils executera la" \
                               " fonction execl et comme chemin '/bin/date/' et avec argument 'date'"
            self.textEdit.setText(explication_execlp)
            resultat = "Affiche la date dans le terminal"
            self.textEdit_2.setText(resultat)
            Execl()

    def clearText(self):
        self.textEdit.clear()
        self.textEdit_2.clear()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
